-- Component Hydration Data for Health Widgets Medical Device Demo
-- Components table schema:
-- CREATE TABLE Components (
--     id INT PRIMARY KEY,
--     componentName VARCHAR(200) NOT NULL,
--     componentDescription VARCHAR(MAX)
-- )

INSERT INTO Components (id, componentName, componentDescription) VALUES
(1, 'TI CC2640 Bluetooth Module',
'Texas Instruments CC2640 Bluetooth Low Energy (BLE) 5.0 wireless SoC. This module handles all wireless communication between Health Widgets medical devices and mobile applications. It runs a proprietary BLE stack with custom GATT profiles for transmitting patient vital signs data. The module includes 128KB flash memory and operates in the 2.4GHz ISM band. Firmware version 1.2.3 is currently deployed across all device models. Security features include AES-128 encryption for BLE pairing and data transmission, though the implementation uses a simplified key exchange protocol for faster pairing in clinical settings.'),

(2, 'Qualcomm WiFi Module',
'Qualcomm Atheros QCA9377 802.11ac dual-band WiFi module used in stationary medical monitoring stations. This component provides network connectivity for hospital-based WidgetMonitor devices to communicate with the central patient monitoring system. The module supports WPA2-Enterprise authentication and operates on both 2.4GHz and 5GHz bands. It runs a customized firmware version 2.0.1 with hospital network optimizations. The WiFi stack includes automatic failover to cellular backup when available. Known to have compatibility issues with certain enterprise WiFi controllers running older firmware.'),

(3, 'STM32 Microcontroller',
'STMicroelectronics STM32F4 series ARM Cortex-M4 microcontroller serving as the main processor for all Health Widgets medical devices. This 32-bit MCU runs at 168MHz and includes 1MB flash memory and 192KB SRAM. It executes the real-time operating system (FreeRTOS) that manages sensor data collection, algorithm processing, and communication protocols. The microcontroller handles critical safety functions including watchdog timers, brownout detection, and fail-safe modes. Hardware cryptographic acceleration is available but not currently utilized. The chip uses a custom bootloader (v3.1) that supports secure firmware updates via encrypted packages.'),

(4, 'Lithium Ion Battery Pack',
'Panasonic NCR18650B 3400mAh lithium-ion battery pack with integrated protection circuit module (PCM). This rechargeable power source provides 3-5 days of continuous operation for portable Health Widgets devices. The battery management system includes overcurrent protection, temperature monitoring, and cell balancing. Communication with the main MCU occurs via I2C protocol to report state of charge and health metrics. The PCM firmware version 1.0 has known limitations in accurately predicting remaining runtime under heavy Bluetooth usage. Battery chemistry is susceptible to performance degradation in extreme temperatures (below 0°C or above 45°C).'),

(5, 'Blood Glucose Sensor',
'Sensirion SFH7060 enzymatic glucose sensor utilizing glucose oxidase enzyme technology for continuous glucose monitoring. This electrochemical sensor measures interstitial fluid glucose levels every 5 minutes with ±15% accuracy in the 40-400 mg/dL range. The sensor has a 14-day lifespan before requiring replacement. Calibration occurs automatically every 12 hours using factory-set baseline values stored in EEPROM. The sensor analog output is sampled by a dedicated 16-bit ADC with programmable gain amplifier. Known to produce erroneous readings during rapid temperature fluctuations or when exposed to certain medications (acetaminophen interference). Sensor data is processed through a proprietary filtering algorithm before transmission.'),

(6, 'Heart Rate Sensor',
'Sensirion SFH2201 photoplethysmography (PPG) optical sensor for continuous heart rate and heart rate variability monitoring. Uses green LED light (525nm) and photodetector to measure blood volume changes in capillaries. Sampling rate of 125Hz enables accurate R-R interval detection for HRV analysis. The sensor includes automatic gain control and ambient light cancellation. Firmware algorithm (v2.3) applies motion artifact reduction using accelerometer data fusion. Accuracy decreases significantly during patient movement or in users with darker skin tones due to reduced signal-to-noise ratio. The sensor communicates with the main MCU via SPI interface at 1MHz clock speed.'),

(7, 'Blood Pressure Sensor',
'Sensirion SDP810 differential pressure sensor adapted for oscillometric blood pressure measurement. This MEMS-based sensor detects pressure oscillations in an inflatable cuff during automated BP measurement cycles. Measurement range of 0-300 mmHg with ±3 mmHg accuracy. The sensor requires factory calibration data stored in internal OTP memory. Pressure readings are sampled at 200Hz during cuff inflation/deflation cycles. Proprietary algorithm (v1.7) extracts systolic, diastolic, and mean arterial pressure from oscillometric waveforms. Known calibration drift issues after 50,000+ measurement cycles. The sensor is sensitive to electrostatic discharge and requires careful ESD protection in the device assembly.'),

(8, 'LCD Display Module',
'3.5-inch TFT LCD touchscreen module with 480x320 resolution and resistive touch controller. This display serves as the primary user interface for Health Widgets medical devices, showing real-time vital signs, graphs, alerts, and configuration menus. The module communicates via 16-bit parallel RGB interface and SPI for touch input. Display driver IC is ILI9488 with 16.7M color support. Backlight LED uses PWM dimming for power conservation. The touchscreen controller (XPT2046) uses 4-wire resistive technology prone to accuracy degradation with screen protector overlays. Graphics rendering is handled by custom UI framework (v3.2) with limited anti-aliasing capabilities. Known occasional ghosting issues when displaying rapidly changing waveforms.'),

(9, 'Secure Enclosure/Case',
'Medical-grade polycarbonate enclosure with IP54 rating for dust and splash resistance. The housing includes integrated tamper detection switches that trigger security alerts if the device is opened outside authorized service procedures. Ultrasonic welded seams prevent moisture intrusion. Internal EMI shielding protects sensitive electronics from RF interference. The case design includes dedicated mounting points for wall-mount or IV pole attachment in clinical settings. Silicone gaskets seal all button and port openings. Tamper switches are connected to GPIO pins on the main MCU and monitored continuously. Opening the enclosure triggers an irreversible security flag in device firmware that requires factory reset and recertification.'),

(10, 'Device Firmware v2.1',
'Embedded firmware for WidgetMonitor multi-parameter vital signs monitor. Built on FreeRTOS v10.4.3 with custom task scheduler for real-time sensor data acquisition and processing. Firmware includes drivers for all sensors, communication protocols (BLE, WiFi), cryptographic functions, and user interface logic. Compiled with GCC ARM 10.3 toolchain with optimization level -O2. Code base approximately 450KB with 85% of available flash utilized. Firmware implements secure boot chain verification using SHA-256 hashing and RSA-2048 signature validation. Over-the-air update mechanism supports delta updates to minimize download size. Known memory leak in the WiFi reconnection logic that can cause device reboot after 72+ hours of continuous operation. Watchdog timer set to 30-second timeout.'),

(11, 'Device Firmware v1.8',
'Embedded firmware for GlucoWidget continuous glucose monitoring device. Specialized real-time firmware optimized for low-power operation and continuous sensor monitoring. Built on custom RTOS kernel with deterministic 5-minute wake cycles for glucose readings. Implements adaptive filtering algorithms to reduce sensor noise and detect rapid glucose changes for alert generation. Firmware size 280KB with 60% flash utilization allowing room for future feature additions. Uses proprietary encryption scheme for BLE data transmission with rolling code authentication. Glucose trend prediction algorithm (v1.4) provides 30-minute forecast with 80% accuracy. Known issue with clock drift causing timestamp inaccuracies over multi-day usage requiring periodic synchronization with mobile app. Battery management optimizations enable 5-day operation on single charge.'),

(12, 'Device Firmware v0.9 (Beta)',
'Beta firmware for WidgetPump insulin delivery system. This is pre-release firmware currently undergoing validation testing and not yet approved for commercial deployment. Implements closed-loop insulin dosing algorithms with PID controller for automated glucose management. Firmware includes safety-critical interlocks, basal/bolus delivery modes, and emergency shutoff mechanisms. Built on safety-certified RTOS with redundant watchdog supervision. Code has undergone static analysis (MISRA-C compliance at 92%) but full IEC 62304 Class C validation is in progress. Contains experimental adaptive dosing algorithm that adjusts insulin delivery based on historical glucose patterns and user activity data from paired fitness trackers. Known instabilities in edge cases of rapid glucose fluctuations. Extensive logging for post-market surveillance and adverse event investigation.'),

(13, 'iOS Mobile App v2.3',
'Native iOS application for iPhone and iPad running iOS 14.0 or later. Developed in Swift 5.5 with SwiftUI framework for modern UI components. The app pairs with GlucoWidget devices via Bluetooth LE, displays real-time glucose readings, generates trend graphs, and provides configurable alerts for hypo/hyperglycemic events. Implements HealthKit integration for sharing glucose data with Apple Health. Local data storage uses Core Data with SQLite backend encrypted with iOS Data Protection. Cloud synchronization occurs via REST API to Health Widgets backend. Push notifications delivered via APNs for critical alerts even when app is backgrounded. Known battery drain issues when maintaining constant BLE connection. App uses third-party charting library (Charts v4.0) with limited customization options. Accessibility support includes VoiceOver for visually impaired users.'),

(14, 'Android Mobile App v2.3',
'Native Android application supporting Android 8.0 (API level 26) and above. Developed in Kotlin with Jetpack Compose UI framework. Functionally equivalent to iOS version with GlucoWidget device pairing, real-time monitoring, and cloud synchronization. Implements Google Fit API integration for health data sharing. Local database uses Room persistence library with SQLCipher for encryption. Firebase Cloud Messaging handles push notifications for alerts. Background service maintains BLE connection for continuous monitoring with Doze mode optimization. Known compatibility issues with certain Samsung devices running custom BLE stack implementations. Uses MPAndroidChart library for data visualization. Adaptive icon support for Android 13+. Occasional ANR (Application Not Responding) errors during large dataset synchronization.'),

(15, 'Cloud API Gateway',
'AWS API Gateway serving as the entry point for all device-to-cloud and mobile-to-cloud communications. Implements RESTful endpoints for device registration, data upload, user authentication, and configuration management. Fronted by CloudFront CDN for global low-latency access. API versioning supports /v1 and /v2 endpoints for backward compatibility. Rate limiting enforced at 1000 requests/minute per device/user to prevent abuse. Request/response payloads are JSON formatted with schema validation. TLS 1.3 encryption terminates at the gateway level. OAuth 2.0 token-based authentication with JWT tokens (15-minute expiration). Lambda functions handle business logic behind the gateway. Known timeout issues during peak usage hours (6-9am) due to Lambda cold starts. DDoS protection via AWS Shield Standard. API usage metrics logged to CloudWatch for monitoring and billing.'),

(16, 'Patient Data Database',
'PostgreSQL 14.5 relational database hosted on AWS RDS (Multi-AZ deployment for high availability). Stores all patient health records, device telemetry, user accounts, and audit logs. Database schema includes 47 tables with proper normalization and referential integrity constraints. Encryption at rest using AES-256 via AWS KMS managed keys. Automated daily backups with 30-day retention and point-in-time recovery capability. Read replicas deployed in two additional regions for geographic redundancy and read scaling. Connection pooling managed by PgBouncer to handle concurrent connections from application servers. Sensitive PHI (Protected Health Information) columns use additional application-layer encryption. Database queries optimized with proper indexing (B-tree, GiST indexes) but some report queries still exhibit slow performance on large datasets. Partition tables implemented for time-series vitals data to improve query performance. Known issue with autovacuum tuning causing temporary query slowdowns during maintenance windows.'),

(17, 'Authentication Service',
'Custom-built identity and access management service implemented as Node.js microservice running on AWS ECS (Elastic Container Service). Handles user registration, login, password reset, and session management for patients, clinicians, and administrators. Implements OAuth 2.0 and OpenID Connect protocols for federated authentication. User credentials stored with bcrypt hashing (cost factor 12) with per-user salt. Multi-factor authentication supported via TOTP (Time-based One-Time Password) using Google Authenticator or SMS codes (Twilio integration). Session tokens are JWTs with RS256 signing algorithm using 2048-bit RSA keys rotated every 90 days. Redis cluster used for session storage and token blacklisting. Known vulnerability to account enumeration via timing attacks in login endpoint (CVE pending). Rate limiting prevents brute force attacks (5 failed attempts trigger 15-minute lockout). HIPAA compliance requires audit logging of all authentication events.'),

(18, 'Alert/Notification Service',
'Real-time alerting and notification microservice built with Node.js and Socket.io for WebSocket connections. Monitors patient vital signs streams for out-of-range values, trend alerts, and device malfunction notifications. Implements configurable alert rules engine with condition thresholds, priority levels (low/medium/high/critical), and escalation policies. Notifications delivered via multiple channels: push notifications (FCM/APNs), SMS (Twilio), email (SendGrid), and in-app WebSocket messages. Critical alerts (e.g., severe hypoglycemia) trigger immediate multi-channel notification with retry logic. Alert fatigue mitigation includes intelligent grouping, snooze functionality, and adaptive threshold adjustment. Event-driven architecture uses Apache Kafka for message queuing with guaranteed delivery. Known latency spikes during high-volume alert storms affecting 100+ patients simultaneously. Alert acknowledgment requires explicit user action logged for regulatory compliance. Integration with PagerDuty for clinical staff on-call escalation.');
